config/routes.rb
Rails.application.routes.draw do
  get 'appointment/index'

  post 'appointment/create'

  get 'appointment/delete'

  get 'appointment/new'

  get 'page_index' => 'page#index', as: :index

  get 'page_help' => 'page#help', as: :help

  get 'online_form' => 'page#form', as: :form

  get 'sell-my-iphone-6-nyc' => 'popular#sell_my_iphone_6', as: :sell_my_iphone_6

  get 'sell-my-iphone-in-nyc' => 'popular#sell_my_iphone_nyc', as: :sell_my_iphone_nyc

  get 'where-to-sell-my-iphone-in-nyc' => 'popular#where_to_sell_iphone_in_nyc', :as => :where_to_sell_my_iphone_in_nyc

  get 'how-to-sell-my-ipad-nyc' => 'popular#how_to_sell_my_ipad', :as => :how_to_sell_my_ipad_nyc

  get 'sell-my-used-ipad-air-nyc' => 'popular#sell_my_used_ipad_air', :as => :sell_my_used_ipad_air

  get 'places-that-buy-iphone-nyc' => 'popular#places_that_buy_iphone_nyc', :as => :places_that_buy_iphone_nyc

  get 'sell-my-iphone-six-plus-nyc' => 'popular#sell_iphone_plus', :as => :sell_iphone_plus

  get 'sell-my-electronics-in-staten-island' => 'popular#sell_staten', as: :sell_staten

  get 'sell-my-electronics-in-long-island' => 'popular#sell_long', as: :sell_long

  get 'pawnshop-that-buys-electronics-in-nyc' => 'popular#pawnshop_that_buys_electronics', :as => :pownshops_that_buy_electronics

  get 'sell-electronics-in-nyc' => 'popular#sell_electronics_in_nyc', :as => :sell_electronics_in_nyc

  get 'new-york-city-electronic-buyers' => 'popular#new_york_city_electronic_buyers', :as => :new_york_city_buyers

  get 'new-york-city-iphone-buyers' => 'popular#nyc_iphone_buyers', :as => :nyc_iphone_buyers

  get 'where-to-sell-macbook-in-nyc' => 'popular#where_to_sell_macbook_in_nyc', :as => :where_to_sell_macbook_in_nyc

  get 'who-buys-electronics-nyc' => 'popular#who_buys_electronics_in_nyc', :as => :who_buys_electronics_in_nyc

  get 'how-to-sell-electronics-in-nyc' => 'popular#how_to_sell_electronics_in_new_york_city', :as => :how_to_sell_electronics_in_new_york_city

  get 'sell-electronics-in-Manhattan' => 'popular#sell_manhattan', :as => :sell_manhattan

  get 'sell-electronics-in-New-Jersey' => 'popular#sell_jersey', :as => :sell_jersey

  get 'sell-my-electronics-in-Connecticut' => 'popular#sell_connecticut', :as => :sell_connecticut

  get 'sell-my-electronics-in-Brooklyn' => 'popular#sell_brooklyn', :as => :sell_brooklyn

  get 'sell-my-electronics-in-queens' => 'popular#sell_electronics_in_queens', :as => :sell_queens

  get 'cell-phone-repair-in-queens' => 'popular#cell_phone_repair_in_queens', :as => :cell_phone_repair

  get 'sell-my-iphone-in-queens' => 'popular#sell_my_iphone_in_queens', :as => :iphone_in_queens

  get 'sell-my-ipad-in-queens' => 'popular#sell_my_ipad_in_queens', :as => :ipad_in_queens

  get 'where-to-fix-my-phone-in-nyc' => 'popular#where_to_fix_my_electronics_in_queens', :as => :cell_phone_repair_where

  get 'where-to-fix-my-iphone-in-queens' => 'popular#iphone_repair_in_queens', :as => :cell_phone_repair_iphone

  get 'where-to-fix-my-samsung-in-queens' => 'popular#fix_samsung_in_queens', :as => :cell_phone_repair_samsung

  get '*unmatched_route', :to => 'page#index'

   root 'page#index'

end

app/views/shared/_footer.html.erb
<section id="contact">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 text-center">
        <h2 class="section-heading">Let's Get In Touch!</h2>
        <hr class="primary">
        <p>Our Queens location works Sunday-Friday from 10 am till 7 pm.
          <!--If you want to come to-->
          <!--our Manhattan location you need to schedule an appointment. Feel free to call us any time. </p>-->
      </div>
      <div class="col-lg-12  text-center">
        <a href="tel:+1-718-846-1600">
          <i class="fa fa-phone fa-3x wow bounceIn"></i>
          <p>718-846-1600</p>
        </a>
      </div>
      <div class="col-lg-12  text-center">
        <a href="https://www.google.com/maps/dir/Current+Location/119-16+Jamaica+Ave+Jamaica+NY+11418">
          <i class="fa fa-map-marker fa-3x wow bounceIn"></i>
          <p>119-16 Jamaica Ave, Jamaica, Queens, NY, 11418</p>
        </a>
      </div>
      <!--<div class="col-lg-12  text-center">-->
        <!--<a href="https://www.google.com/maps/place/71+W+47th+St,+New+York,+NY+10036+Suite+302">-->
          <!--<i class="fa fa-map-marker fa-3x wow bounceIn"></i>-->
          <!--<p>71 West 47 Street (Suite 302), Midtown, New York, NY, 10036 </p>-->
        <!--</a>-->
      <!--</div>-->
      <div class="col-lg-12  text-center">
        <a href="mailto:8710leffertsblvd@gmail.com">
          <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
          <p>8710leffertsblvd@gmail.com</p>
        </a>
      </div>
    </div>
  </div>

</section>



<h3 class="text-center">POPULAR SEARCHES</h3>
<hr class="primary">
<section id="popularsearch" class="text-center">
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <%= link_to "Sell my iPhone 6", sell_my_iphone_6_path %> <br/>
        <%= link_to "Sell my iPhone in NYC", sell_my_iphone_nyc_path %> <br/>
        <%= link_to "Sell iPhone 6 plus", sell_iphone_plus_path %> <br/>
        <%= link_to "Where to sell used iPhone in NYC", where_to_sell_my_iphone_in_nyc_path %> <br/>
        <%= link_to "How to sell my iPad", how_to_sell_my_ipad_nyc_path %> <br/>
        <%= link_to "Sell my used iPad Air", sell_my_used_ipad_air_path %> <br/>
        <%= link_to "Places that buy used iPhones", places_that_buy_iphone_nyc_path %> <br/>
        <%= link_to "Sell Electronics in Long Island", sell_long_path %> <br/>
        <%= link_to "Sell Electronics in Staten Island", sell_staten_path %> <br/>
      </div>
      <div class="col-sm-4">
        <%= link_to "Pawnshops that buy electronics", pownshops_that_buy_electronics_path %> <br/>
        <%= link_to "Sell electronics in NYC", sell_electronics_in_nyc_path %> <br/>
        <%= link_to "New York City electronics buyers", new_york_city_buyers_path %> <br/>
        <%= link_to "NYC buyers of electronics", nyc_iphone_buyers_path %> <br/>
        <%= link_to "Where to sell MacBook pro in NYC", where_to_sell_macbook_in_nyc_path %> <br/>
        <%= link_to "Who buys electronics in NYC", who_buys_electronics_in_nyc_path %> <br/>
        <%= link_to "How to sell electronics in New York", how_to_sell_electronics_in_new_york_city_path %> <br/>
        <%= link_to "Sell Electronics in Manhattan", sell_manhattan_path %> <br/>
        <%= link_to "Sell Electronics in New Jersey", sell_jersey_path %> <br/>
      </div>
      <div class="col-sm-4">
        <%= link_to "Sell electronics in Queens", sell_queens_path %> <br/>
        <%= link_to "Cell phone repair in Queens", cell_phone_repair_path %> <br/>
        <%= link_to "Where to fix my electronics in Queens", cell_phone_repair_where_path %> <br/>
        <%= link_to "iPhone repair in Queens", cell_phone_repair_iphone_path %> <br/>
        <%= link_to "Fix Samsung in Queens", cell_phone_repair_samsung_path %> <br/>
        <%= link_to "Sell my iPhone in Queens", iphone_in_queens_path %> <br/>
        <%= link_to "Sell my iPad in Queens", ipad_in_queens_path %> <br/>
        <%= link_to "Sell Electronics in Connecticut", sell_connecticut_path %> <br/>
        <%= link_to "Sell Electronics in Brooklyn", sell_brooklyn_path %> <br/>
      </div>
    </div>
  </div>
</section>


<p class="text-center">Copyright © 2015 SellElectronics.NYC inc</p>

app/views/shared/_navbar.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand page-scroll" href="/">SellElectronics.NYC</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a class="page-scroll" href="/"> << Main Page</a>
        </li>
        <li>
          <a class="page-scroll" href="/#services">How it works?</a>
        </li>
        <li>
          <a class="page-scroll" href="">What We Buy</a>
        </li>
        <li>
          <a class="page-scroll" href="#contact">Contacts</a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/shared/_popular_search.html.erb
<header>
  <div class="header-content">
    <div class="header-content-inner">
      <h1><%= @h1 %></h1>
      <hr>
      <p><%= @main_p %></p>
      <a href="tel:+1-718-846-1600" class="btn btn-primary btn-xl page-scroll"><i class="fa fa-phone"></i> CLICK TO CALL =>></a> <br/>
      <br/>
    </div>
  </div>
</header>

<section class="bg-primary" id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 text-center">
        <h2 class="section-heading">Sell your items right now!</h2>
        <hr class="light">
        <p class="text-faded"> Electronic items lose value every single second, if you do not use something, better sell it.
          Nobody wants to buy "items from yestarday", do not waste your time and money, call us right now.</p>
        <a href="#" class="btn btn-default btn-xl">learn more =>></a>
      </div>
    </div>
  </div>
</section>